#ifndef OTHER_FILES
#define OTHER_FILES

extern unsigned char CODE_ENTRANCE_CUTSCENE_TABLE_BIN[];
#define CODE_ENTRANCE_CUTSCENE_TABLE_BIN_LEN 300

extern unsigned char CODE_ENTRANCE_TABLE_BIN[];
#define CODE_ENTRANCE_TABLE_BIN_LEN 6224

extern unsigned char CODE_OVERWORLD_MINIMAP_TABLE_COMPASS_BIN[];
#define CODE_OVERWORLD_MINIMAP_TABLE_COMPASS_BIN_LEN 192

extern unsigned char CODE_OVERWORLD_MINIMAP_TABLE_HEIGHT_BIN[];
#define CODE_OVERWORLD_MINIMAP_TABLE_HEIGHT_BIN_LEN 48

extern unsigned char CODE_OVERWORLD_MINIMAP_TABLE_LENGTH_BIN[];
#define CODE_OVERWORLD_MINIMAP_TABLE_LENGTH_BIN_LEN 48

extern unsigned char CODE_OVERWORLD_MINIMAP_TABLE_OFFSET_BIN[];
#define CODE_OVERWORLD_MINIMAP_TABLE_OFFSET_BIN_LEN 48

extern unsigned char CODE_OVERWORLD_MINIMAP_TABLE_WIDTH_BIN[];
#define CODE_OVERWORLD_MINIMAP_TABLE_WIDTH_BIN_LEN 48

extern unsigned char CODE_OVERWORLD_MINIMAP_TABLE_XPOS_BIN[];
#define CODE_OVERWORLD_MINIMAP_TABLE_XPOS_BIN_LEN 48

extern unsigned char CODE_OVERWORLD_MINIMAP_TABLE_YPOS_BIN[];
#define CODE_OVERWORLD_MINIMAP_TABLE_YPOS_BIN_LEN 48

extern unsigned char DEFAULT_SAVE_DATA_BIN[];
#define DEFAULT_SAVE_DATA_BIN_LEN 170

extern unsigned char PAUSE_ITEM_USABILITY_BIN[];
#define PAUSE_ITEM_USABILITY_BIN_LEN 128

#endif // OTHER_FILES
