#ifndef OBJECT_FILES
#define OBJECT_FILES

extern unsigned char GAMEPLAY_DANGEON_KEEP_BIN[];
#define GAMEPLAY_DANGEON_KEEP_BIN_LEN 97008

extern unsigned char OBJECT_FD_NTSC_BIN[];
#define OBJECT_FD_NTSC_BIN_LEN 66160

extern unsigned char OBJECT_GI_BRACELET_BIN[];
#define OBJECT_GI_BRACELET_BIN_LEN 3056

extern unsigned char OBJECT_GI_CLOTHES_BIN[];
#define OBJECT_GI_CLOTHES_BIN_LEN 6240

extern unsigned char OBJECT_GI_SHIELD_1_BIN[];
#define OBJECT_GI_SHIELD_1_BIN_LEN 2720

extern unsigned char OBJECT_GI_SHIELD_2_BIN[];
#define OBJECT_GI_SHIELD_2_BIN_LEN 4688

extern unsigned char OBJECT_LINK_CHILD_BIN[];
#define OBJECT_LINK_CHILD_BIN_LEN 184192

extern unsigned char GAMEPLAY_KEEP_LINKHAIR_1A40_BIN[];
#define GAMEPLAY_KEEP_LINKHAIR_1A40_BIN_LEN 2048

extern unsigned char OBJECT_BDOOR_TEX_3600_65C0_BIN[];
#define OBJECT_BDOOR_TEX_3600_65C0_BIN_LEN 4096

extern unsigned char OBJECT_BOX_TEX_2F98_BIN[];
#define OBJECT_BOX_TEX_2F98_BIN_LEN 6144

extern unsigned char OBJECT_FD2_PAL_2508_BIN[];
#define OBJECT_FD2_PAL_2508_BIN_LEN 512

extern unsigned char OBJECT_FD2_TEX_3308_BIN[];
#define OBJECT_FD2_TEX_3308_BIN_LEN 2048

extern unsigned char OBJECT_FD2_TEX_4308_BIN[];
#define OBJECT_FD2_TEX_4308_BIN_LEN 512

extern unsigned char OBJECT_FD2_TEX_4508_BIN[];
#define OBJECT_FD2_TEX_4508_BIN_LEN 512

extern unsigned char OBJECT_FD2_TEX_4708_BIN[];
#define OBJECT_FD2_TEX_4708_BIN_LEN 512

extern unsigned char OBJECT_FD2_TEX_4908_BIN[];
#define OBJECT_FD2_TEX_4908_BIN_LEN 512

extern unsigned char OBJECT_FD2_TEX_4FA0_BIN[];
#define OBJECT_FD2_TEX_4FA0_BIN_LEN 512

extern unsigned char OBJECT_FD2_TEX_51A0_BIN[];
#define OBJECT_FD2_TEX_51A0_BIN_LEN 512

extern unsigned char OBJECT_FD2_TEX_53A0_BIN[];
#define OBJECT_FD2_TEX_53A0_BIN_LEN 512

extern unsigned char OBJECT_HIDAN_OBJECTS_TEX_5240_BIN[];
#define OBJECT_HIDAN_OBJECTS_TEX_5240_BIN_LEN 1024

extern unsigned char OBJECT_HIDAN_OBJECTS_TEX_5640_BIN[];
#define OBJECT_HIDAN_OBJECTS_TEX_5640_BIN_LEN 1024

extern unsigned char OBJECT_HIDAN_OBJECTS_TEX_6A40_BIN[];
#define OBJECT_HIDAN_OBJECTS_TEX_6A40_BIN_LEN 512

extern unsigned char OBJECT_HIDAN_OBJECTS_TEX_A40_BIN[];
#define OBJECT_HIDAN_OBJECTS_TEX_A40_BIN_LEN 18432

extern unsigned char OBJECT_MIZU_OBJECTS_TEX_8520_BIN[];
#define OBJECT_MIZU_OBJECTS_TEX_8520_BIN_LEN 2048

extern unsigned char OBJECT_MIZU_OBJECTS_TEX_AB20_BIN[];
#define OBJECT_MIZU_OBJECTS_TEX_AB20_BIN_LEN 2048

extern unsigned char OBJECT_PO_COMPOSER_TEX_56E0_BIN[];
#define OBJECT_PO_COMPOSER_TEX_56E0_BIN_LEN 512

extern unsigned char OBJECT_PO_COMPOSER_TEX_68E0_BIN[];
#define OBJECT_PO_COMPOSER_TEX_68E0_BIN_LEN 512

extern unsigned char OBJECT_SD_PAL_5C40_BIN[];
#define OBJECT_SD_PAL_5C40_BIN_LEN 512

extern unsigned char OBJECT_SD_TEX_60C0_BIN[];
#define OBJECT_SD_TEX_60C0_BIN_LEN 512

extern unsigned char OBJECT_SD_TEX_62C0_BIN[];
#define OBJECT_SD_TEX_62C0_BIN_LEN 1024

extern unsigned char OBJECT_SPOT02_OBJECTS_TEX_13420_BIN[];
#define OBJECT_SPOT02_OBJECTS_TEX_13420_BIN_LEN 1024

#endif // OBJECT_FILES
