#ifndef SCENE_FILES
#define SCENE_FILES

extern unsigned char CAVE_PASSAGE_ROOM_0_ZMAP[];
#define CAVE_PASSAGE_ROOM_0_ZMAP_LEN 25792

extern unsigned char CAVE_PASSAGE_ZSCENE[];
#define CAVE_PASSAGE_ZSCENE_LEN 43888

extern unsigned char CREDITS_ROOM_0_ZMAP[];
#define CREDITS_ROOM_0_ZMAP_LEN 528

extern unsigned char CREDITS_ZSCENE[];
#define CREDITS_ZSCENE_LEN 2848

extern unsigned char CUTSCENE_MAP_ROOM_0_ZMAP[];
#define CUTSCENE_MAP_ROOM_0_ZMAP_LEN 66832

extern unsigned char CUTSCENE_MAP_ZSCENE[];
#define CUTSCENE_MAP_ZSCENE_LEN 265136

extern unsigned char DAWNGROVE_HOUSE_1_ROOM_0_ZMAP[];
#define DAWNGROVE_HOUSE_1_ROOM_0_ZMAP_LEN 7760

extern unsigned char DAWNGROVE_HOUSE_1_ZSCENE[];
#define DAWNGROVE_HOUSE_1_ZSCENE_LEN 19680

extern unsigned char DAWNGROVE_HOUSE_2_ROOM_0_ZMAP[];
#define DAWNGROVE_HOUSE_2_ROOM_0_ZMAP_LEN 16832

extern unsigned char DAWNGROVE_HOUSE_2_ZSCENE[];
#define DAWNGROVE_HOUSE_2_ZSCENE_LEN 29120

extern unsigned char DAWNGROVE_INN_ROOM_0_ZMAP[];
#define DAWNGROVE_INN_ROOM_0_ZMAP_LEN 20640

extern unsigned char DAWNGROVE_INN_ROOM_1_ZMAP[];
#define DAWNGROVE_INN_ROOM_1_ZMAP_LEN 12208

extern unsigned char DAWNGROVE_INN_ROOM_2_ZMAP[];
#define DAWNGROVE_INN_ROOM_2_ZMAP_LEN 9632

extern unsigned char DAWNGROVE_INN_ROOM_3_ZMAP[];
#define DAWNGROVE_INN_ROOM_3_ZMAP_LEN 6464

extern unsigned char DAWNGROVE_INN_ROOM_4_ZMAP[];
#define DAWNGROVE_INN_ROOM_4_ZMAP_LEN 16192

extern unsigned char DAWNGROVE_INN_ROOM_5_ZMAP[];
#define DAWNGROVE_INN_ROOM_5_ZMAP_LEN 34640

extern unsigned char DAWNGROVE_INN_ZSCENE[];
#define DAWNGROVE_INN_ZSCENE_LEN 119232

extern unsigned char DAWNGROVE_ROOM_0_ZMAP[];
#define DAWNGROVE_ROOM_0_ZMAP_LEN 28016

extern unsigned char DAWNGROVE_ROOM_1_ZMAP[];
#define DAWNGROVE_ROOM_1_ZMAP_LEN 46304

extern unsigned char DAWNGROVE_ROOM_2_ZMAP[];
#define DAWNGROVE_ROOM_2_ZMAP_LEN 14672

extern unsigned char DAWNGROVE_SHOP_ROOM_0_ZMAP[];
#define DAWNGROVE_SHOP_ROOM_0_ZMAP_LEN 4784

extern unsigned char DAWNGROVE_SHOP_ZSCENE[];
#define DAWNGROVE_SHOP_ZSCENE_LEN 19744

extern unsigned char DAWNGROVE_VILLAGE_ROOM_0_ZMAP[];
#define DAWNGROVE_VILLAGE_ROOM_0_ZMAP_LEN 48496

extern unsigned char DAWNGROVE_VILLAGE_ZSCENE[];
#define DAWNGROVE_VILLAGE_ZSCENE_LEN 75392

extern unsigned char DAWNGROVE_ZSCENE[];
#define DAWNGROVE_ZSCENE_LEN 108416

extern unsigned char DUSK_PALACE_CHAMBER_ROOM_0_ZMAP[];
#define DUSK_PALACE_CHAMBER_ROOM_0_ZMAP_LEN 33264

extern unsigned char DUSK_PALACE_CHAMBER_ZSCENE[];
#define DUSK_PALACE_CHAMBER_ZSCENE_LEN 34000

extern unsigned char DUSK_PALACE_GARDENS_ROOM_0_ZMAP[];
#define DUSK_PALACE_GARDENS_ROOM_0_ZMAP_LEN 75136

extern unsigned char DUSK_PALACE_GARDENS_ZSCENE[];
#define DUSK_PALACE_GARDENS_ZSCENE_LEN 74448

extern unsigned char GREAT_DUSK_CHASM_ROOM_0_ZMAP[];
#define GREAT_DUSK_CHASM_ROOM_0_ZMAP_LEN 27888

extern unsigned char GREAT_DUSK_CHASM_ROOM_1_ZMAP[];
#define GREAT_DUSK_CHASM_ROOM_1_ZMAP_LEN 37424

extern unsigned char GREAT_DUSK_CHASM_ROOM_2_ZMAP[];
#define GREAT_DUSK_CHASM_ROOM_2_ZMAP_LEN 27200

extern unsigned char GREAT_DUSK_CHASM_ZSCENE[];
#define GREAT_DUSK_CHASM_ZSCENE_LEN 69072

extern unsigned char GROTTOS_ROOM_13_ZMAP[];
#define GROTTOS_ROOM_13_ZMAP_LEN 28368

extern unsigned char GROTTOS_ZSCENE[];
#define GROTTOS_ZSCENE_LEN 55328

extern unsigned char RED_ICE_CAVERN_ROOM_0_ZMAP[];
#define RED_ICE_CAVERN_ROOM_0_ZMAP_LEN 19712

extern unsigned char RED_ICE_CAVERN_ROOM_1_ZMAP[];
#define RED_ICE_CAVERN_ROOM_1_ZMAP_LEN 8224

extern unsigned char RED_ICE_CAVERN_ROOM_2_ZMAP[];
#define RED_ICE_CAVERN_ROOM_2_ZMAP_LEN 10176

extern unsigned char RED_ICE_CAVERN_ROOM_3_ZMAP[];
#define RED_ICE_CAVERN_ROOM_3_ZMAP_LEN 16784

extern unsigned char RED_ICE_CAVERN_ROOM_4_ZMAP[];
#define RED_ICE_CAVERN_ROOM_4_ZMAP_LEN 8144

extern unsigned char RED_ICE_CAVERN_ROOM_5_ZMAP[];
#define RED_ICE_CAVERN_ROOM_5_ZMAP_LEN 22880

extern unsigned char RED_ICE_CAVERN_ZSCENE[];
#define RED_ICE_CAVERN_ZSCENE_LEN 112560

#endif // SCENE_FILES
